url: https://jonasharsch.github.io/
baseurl: 

# Site Settings
title: Jonas Harsch
author: I’m a simulation technology master student at university stuttgart. My key interest are  **Nonlinear continuum mechanis**, **Parallel computing** (implementation of parallel numerical solver using *MPI*, *OpenCL* and *CUDA*), **Isogeometric analysis** and **Programming** (*C++*, *fortran*, *python*, *cmake*).
description: "My name is Jonas Harsch. I’m a simulation technology student of university stuttgart."
keywords: "Jonas, Harsch, simulation, technology, continuum, mechanics, Stuttgart, university, C++, beam, nonlinear, FE, Finite Elements, Implementation"
google-tracking-id:

# Default career image.
default-img: "img/timeline/default.png"

# Author image
author-img: "img/author/author2.png"

# Baby/ Beginning image
baby-img: "img/timeline/baby.png"

collections:
  education:
  work:

exclude: ["LICENSE"]

# Define plugins
plugins:
  - jekyll-seo-tag